### ISSUE TITLE
Provide option/example to launch nav2 as composed nodes

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#1244] opened 2019-10-15 20:48 UTC
#### Feature description

As described by the title, provide the capability to launch the stack as a composition of nodes.

In general, we have to: 
- [ ] [Register](https://index.ros.org/doc/ros2/Tutorials/Composition/#writing-a-component) the nodes as components #1013
- [ ] Use the components to run the stack. Define which [option](https://index.ros.org/doc/ros2/Tutorials/Composition/#using-components) to use and implement.

**Comment by bpwilcox** [comment] 2019-10-15 21:43
duplicate of #1013?

**Comment by orduno** [comment] 2019-10-16 16:45
> duplicate of #1013?

I don't think it's a duplicate. If I understand correctly, it's at least a two-step process. I've updated the ticket.

**Comment by SteveMacenski** [comment] 2019-10-16 17:18
I'd consider it one ticket since you really wouldn't know if you did it right without making the launch file to test

regardless, +1000. In the near future I have to finish porting image_pipeline to ROS2 + components so I'll be watching closely to take your lead. 

![img](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

**Comment by SteveMacenski** [comment] 2020-08-11 19:11
https://github.com/ros-planning/navigation2/issues/1013 Closing in favor of a single component feature request ticker

**Closed by SteveMacenski** 2020-08-11 19:11 UTC
