### ISSUE TITLE
Implement ROSRobot functionality

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#55] opened 2018-09-05 18:19 UTC
Right now ROSRobot is an empty shell class with no functionality. It needs to be defined and implemented or the code should be removed.

**Comment by mjeronimo** [comment] 2018-09-06 04:08
This is a duplicate of #22 "Define Robot class and interface"

**Closed** 2018-09-06 04:09 UTC
Labels: bug

**Comment by mkhansen-intel** [comment] 2018-09-06 14:48
I thought the other one was definition / design and this is implementation, however I'm fine with closing if the other one will cover this.
