### ISSUE TITLE
Wiki page for detailing defaults of parameters and/or recommended values 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#690] opened 2019-05-07 21:34 UTC

**Comment by crdelsey** [comment] 2019-05-08 18:11
There was some push back in the working group on using the wiki for documentation. The suggestion was to use the same mechanism that OSRF is using for ROS 2 documentation or [Read the Docs](https://readthedocs.org/). I think in the meantime, just adding a markdown file in our docs directory is the way to go

**Comment by SteveMacenski** [comment] 2019-05-08 20:39
This would also be the Wiki built into the repository as well. Read the docs would be great as well.

**Comment by crdelsey** [comment] 2019-10-28 21:43
Dupe of #1305

**Closed by crdelsey** 2019-10-28 21:43 UTC
Labels: 1 - High, documentation
