### ISSUE TITLE
BT Plugin for changing the robot footprint at runtime

### ISSUE THREAD

**Issue by guilyx** [ros-planning/navigation2#2626] opened 2021-10-19 15:49 UTC
Hi,

#### Feature description
Discussed this on the slack this summer, but focus had changed at that point and had no time to go back to it since then. The idea is to have a Behaviour Tree Plugin that allows to change the footprint of the robot. In our specific case the robot parks under trolleys, lift an actuator and carries those trolleys from A to B, so the footprint has to be dynamic and situational, changed in the BT. 

#### Implementation considerations

- It would transition local/global costmaps nodes to unconfigure
- Change the parameters (and depending on the footprint model, check if all the fields are there in the node)
- Transition local/global costmaps nodes to configure then activate

We use TEB and TEB has a footprint parameter too, so I guess the controller planner would need to be reconfigured too if TEB is among the controller plugins

Even though @SteveMacenski already said sure do it, figured I'd open an issue that I can see everyday rather than slack that I rarely check. Just need confirmation with the implementation considerations as I have never used reconfigure at run time, maybe there's a better/faster/easier way.

**Comment by SteveMacenski** [comment] 2021-10-19 22:47
@doisyg you also work with changing footprints, do you have some thoughts on this?

**Comment by padhupradheep** [comment] 2022-01-12 13:22
> e.g. how does the BT get the new footprint to update it to? A topic?

Maybe just have a parameter for the BT node and add the footprint. Something like as follows:

```<UpdateFootprint name="FootprintUpdate" footprint="[[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]" topic_name="global_costmap/footprint"/>```` 

Then we can design the `UpdateFootprint` BT node to publish to the footprint topic specified by the user.

**Comment by padhupradheep** [comment] 2022-01-12 13:25
> e.g. how does the BT get the new footprint to update it to? A topic?

Maybe just have a parameter for the BT node for updating the footprint and the topic to which it needs to publish. Something like as follows:

`<UpdateFootprint name="FootprintUpdate" footprint="[[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]" topic_name="global_costmap/footprint"/>`

**Comment by SteveMacenski** [comment] 2022-01-12 21:27
I'm not sure the path forward for this. How would this BT node _get_ the footprint itself to be publishing to other topics? A topic? If that's the case, then someone is already publishing the footprint, they should just publish it directly to the costmap and there's no need for this to be in the behavior tree. The ways to get the info in the behavior tree would probably also work for communicating it to the costmaps directly.

The only situation I see that this would be useful uniquely would be if you had a static footprint that you were adding to the behavior tree itself -- so it wasn't dynamically changing -- and you may have multiple of these in the BT based on the current state. That seems a little messy but maybe that's what @guilyx wanted? 

Otherwise, I would vote to close this ticket since I'm not sure if we have `server_A` publishing to the BT the footprint why it couldn't just publish to the costmaps themselves

**Comment by padhupradheep** [comment] 2022-01-13 06:59
>The only situation I see that this would be useful uniquely would be if you had a static footprint that you were adding to the behavior tree itself -- so it wasn't dynamically changing -- and you may have multiple of these in the BT based on the current state. That seems a little messy but maybe that's what @guilyx wanted?

This makes a lot of sense to me. I will try to elaborate a little bit more on thoughts which I developed based on the explanation given by @guilyx. Having a robot that goes under the trolley, does the dock, once the docking is finished, you change the footprint depending on the size of the trolley. Although, assuming there is no magic for determining the size of the trolley, but rather being a (pre-calculated and suitable) manual footprint given to the `ChangeFootprint` BT node. Similarly you navigate through different poses, and in each of these different poses you either dock or undock the trolley and change the footprint of the robot depending upon the dimensions of the trolley. Of course, as a system designer, here you definitely need to know your BT workflow on where and when your robot will be dock../undocking with the trolley's of different dimensions. 

Since we do not have a `docking` BT yet in the stack, for now people can just use the `GoalReached` BT, do the docking externally, and just use the `ChangeFootprint` BT-Node to change the footprint. 

There maybe a point on "why not do the footprint change externally as well?" Thinking on a big-picture with docking BT's probably ending up in the stack within a year or two, this will be useful then. This BT maybe also useful in other applications.

**Comment by guilyx** [comment] 2022-01-13 10:20
As @doisyg pointed out

> Because we do it through dynamic parameters, the changes are immediate and we don't need to cycle through unconfigure

The BT Action would just change the parameters of the footprint dynamically in Costmap2D ? For Nav2 specifically (and not using TEB) then you only need to change the Costmap footprint parameter. 
Basically we have a way of detecting the trolley on top of the robot and we want to change the footprint in Costmap2D to that detected footprint.

The dynamic parameters PR already made it possible for everyone to implement their own BT Plugin for this I think, but this was pushed back in our backlog so I haven't developed anything yet.

All I know is that the use case is the same as @doisyg at Wyca, and it looks like in the current state of the Galactic Branch they could do it with PR #2592.

**Comment by doisyg** [comment] 2022-01-13 11:56
> All I know is that the use case is the same as @doisyg at Wyca, and it looks like in the current state of the Galactic Branch they could do it with PR #2592.

I can confirm ;), we use it everyday and it works great

> For Nav2 specifically (and not using TEB) then you only need to change the Costmap footprint parameter.

I made the change for TEB to catch the dynamic footprint param in our fork, if there is enough interests, I can PR it. Though there are a couple of maintenance tasks to take care of also (in TEB) and I am a bit tight in time these days.

**Comment by SteveMacenski** [comment] 2022-01-13 22:01
>  you change the footprint depending on the size of the trolley

I think that only works if you're only changing by a small number of discrete sizes (e.g. only 1 or 2 types of trolleys). If its any more variable than that - like if you had a mobile manipulator - you may be better off with a state publisher updating the footprint dynamically itself. 

> then you only need to change the Costmap footprint parameter

Or a topic, there's an input footpritnt topic to costmap that you can use to change the footprint from another source, as discussed above.

---

I see the value of having something to change the footprint, but I'm just not seeing how the BT would **get** that info to communicate other than by methods that would make sense for the publisher to directly inform the costmap itself -- except for statically set changes. 

If statically set changes are all you want, I'd merge that PR now. Otherwise, we should discuss the design mechanisms that make this useful.

**Comment by SteveMacenski** [comment] 2022-03-24 00:09
Closing after the design discussion - it doesn't seem like this is the right place for these semantics. Happy to reopen if there's more discussion to be had, but we haven't had an update in months and there are non-trivial open implementation questions

**Closed by SteveMacenski** 2022-03-24 00:09 UTC
