### ISSUE TITLE
source navigation2 build error

### ISSUE THREAD

**Issue by gokul-gokz** [ros-planning/navigation2#1771] opened 2020-05-27 01:08 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04  ,ROS Distro -eloquent
- Version or commit hash:
  - de0ed9aa85ae912cdb85e7eb12fb96dbdaa53c88

- DDS implementation:
  - 

#### Steps to reproduce issue
Followed the source installation of naviagation2

#### Error

```
--- stderr: nav2_map_server                                                
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp: In member function ‘typename T::Response::SharedPtr MapServerTestFixture::send_request(rclcpp::Node::SharedPtr, typename rclcpp::Client<ServiceT>::SharedPtr, typename T::Request::SharedPtr)’:
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp:72:69: error: ‘rclcpp::FutureReturnCode’ has not been declared
     if (rclcpp::spin_until_future_complete(node, result) == rclcpp::FutureReturnCode::SUCCESS) {
                                                                     ^~~~~~~~~~~~~~~~
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_saver_node.cpp: In member function ‘typename T::Response::SharedPtr MapSaverTestFixture::send_request(rclcpp::Node::SharedPtr, typename rclcpp::Client<ServiceT>::SharedPtr, typename T::Request::SharedPtr)’:
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_saver_node.cpp:74:69: error: ‘rclcpp::FutureReturnCode’ has not been declared
     if (rclcpp::spin_until_future_complete(node, result) == rclcpp::FutureReturnCode::SUCCESS) {
                                                                     ^~~~~~~~~~~~~~~~
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_saver_node.cpp: In member function ‘typename T::Response::SharedPtr MapSaverTestFixture::send_request(rclcpp::Node::SharedPtr, typename rclcpp::Client<ServiceT>::SharedPtr, typename T::Request::SharedPtr) [with T = nav2_msgs::srv::SaveMap]’:
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_saver_node.cpp:79:3: error: control reaches end of non-void function [-Werror=return-type]
   }
   ^
cc1plus: all warnings being treated as errors
make[2]: *** [test/component/CMakeFiles/test_map_saver_node.dir/test_map_saver_node.cpp.o] Error 1
make[1]: *** [test/component/CMakeFiles/test_map_saver_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp: In member function ‘typename T::Response::SharedPtr MapServerTestFixture::send_request(rclcpp::Node::SharedPtr, typename rclcpp::Client<ServiceT>::SharedPtr, typename T::Request::SharedPtr) [with T = nav_msgs::srv::GetMap]’:
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp:77:3: error: control reaches end of non-void function [-Werror=return-type]
   }
   ^
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp: In member function ‘typename T::Response::SharedPtr MapServerTestFixture::send_request(rclcpp::Node::SharedPtr, typename rclcpp::Client<ServiceT>::SharedPtr, typename T::Request::SharedPtr) [with T = nav2_msgs::srv::LoadMap]’:
/home/gokul/navigation2_ws/src/navigation2/nav2_map_server/test/component/test_map_server_node.cpp:77:3: error: control reaches end of non-void function [-Werror=return-type]
   }
   ^
cc1plus: all warnings being treated as errors
make[2]: *** [test/component/CMakeFiles/test_map_server_node.dir/test_map_server_node.cpp.o] Error 1
make[1]: *** [test/component/CMakeFiles/test_map_server_node.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< nav2_map_server	[ Exited with code 2 ]
Aborted  <<< nav2_rviz_plugins                     
Aborted  <<< nav2_amcl                             
Aborted  <<< nav2_behavior_tree          
```

**Comment by SteveMacenski** [comment] 2020-05-27 01:30
Please follow build instructions https://navigation.ros.org/build_instructions/index.html#manually-build-master

You're building ROS2 master on eloquent binaries, which is not supported (and now out of sync so it doesn't work). 

We can keep chatting here but closing the ticket because its not a bug but a your dev environment

**Closed by SteveMacenski** 2020-05-27 01:30 UTC
