### ISSUE TITLE
Newly flaky tests

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1436] opened 2019-12-13 01:08 UTC
## Bug report

The following tests are now failing frequently in CI and locally, on the master branch and the eloquent branch:
 - [x] nav2_util test_actions
 - [x] nav2_recoveries test_recoveries
 - [ ] nav2_system_tests test_waypoint_follower

Here's a build that demonstrates all three failures:
https://circleci.com/gh/ros-planning/navigation2/7136?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SteveMacenski** [comment] 2020-02-04 00:51
Closing in favor of #1489 that is root cause,

**Closed by SteveMacenski** 2020-02-04 00:51 UTC
