### ISSUE TITLE
Implement persistence for localization pose

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#698] opened 2019-05-09 15:13 UTC
#### Feature description
Previously, the AMCL code save the last known pose to a parameter server. With ROS2, we should decide how to implement persistance for AMCL (and other modules) so the robot starts up with its last known pose.

**Comment by crdelsey** [comment] 2019-05-13 21:48
Duplicate of #290

**Closed by crdelsey** 2019-05-13 21:48 UTC
