### ISSUE TITLE
Is this a bug that  ROS2_DISTRO is set to "dashing" for the "eloquent-devel" branch?

### ISSUE THREAD

**Issue by ByLiZhao** [ros-planning/navigation2#2132] opened 2020-12-21 14:25 UTC
https://github.com/ros-planning/navigation2/blob/3ac28606f0d8f9f12d46a74b616b81a382724142/tools/initial_ros_setup.sh#L7

**Comment by SteveMacenski** [comment] 2020-12-21 15:51
Duplicate of #2133

**Closed by SteveMacenski** 2020-12-21 15:51 UTC
