### ISSUE TITLE
Navigation 2 run on ramps

### ISSUE THREAD

**Issue by Andrea2202** [ros-planning/navigation2#1929] opened 2020-08-09 10:58 UTC
## Info request

**Required Info:**

- Operating System:
 Ubuntu 18.04
- ROS2 Version:
 Foxy source code
- Version or commit hash:
  - 

## Feature request

Hi all, 
I'm using ros2 and navigation2 for an indoor differential drive robot.
Currently the main limit of my system is that I'm not able to run ramps.
I need to move on ramps up to 6%.

Do you know if there are modules or plugins for ros2 or navigation2 that allow to navigate on ramps?
I's under development this feature on navigation2?
Or if not have you in mind a way to integrate this feature in the cirrent nav2 implementation? 

Thanks

**Comment by SteveMacenski** [comment] 2020-08-10 20:35
Not currently a supported feature

**Comment by Andrea2202** [comment] 2020-08-11 10:45
Hi @SteveMacenski, 
Thanks for your answer.
Have you in mind some way to easly integrate  this feature in the current navigation2 stack?
Or can you provide us a path to follow in order to implement ourself this feature?

Thanks in advance

**Comment by SteveMacenski** [comment] 2020-08-11 16:37
I don't at this time. This is duplicate of #1224 asking for non-flat navigation, so I'll close this ticket but we can move discussion back over there.

**Closed by SteveMacenski** 2020-08-11 16:37 UTC
